import { Brain, Shield, Eye, Lock, Users, Mail } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import HeaderComponent from '@/components/header';

export const metadata = {
  title: 'Privacy Policy | ResumeBolt - How We Protect Your Data',
  description: 'Learn how ResumeBolt protects your privacy and handles your data. Comprehensive privacy policy covering data collection, processing, and your rights under GDPR.',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <HeaderComponent />

      {/* Privacy Policy Content */}
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="max-w-4xl mx-auto">
          {/* Header Section */}
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
            <p className="text-xl text-muted-foreground">
              Your privacy is important to us. This policy explains how we collect, use, and protect your information.
            </p>
            <p className="text-sm text-muted-foreground mt-2">
              <strong>Last updated:</strong> January 2025
            </p>
          </div>

          {/* Quick Overview Cards */}
          <div className="grid md:grid-cols-3 gap-6 mb-12">
            <Card>
              <CardHeader className="text-center">
                <Shield className="h-8 w-8 text-green-500 mx-auto mb-2" />
                <CardTitle className="text-lg">We Don't Store Your Docs</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground text-center">
                  Your resumes and job descriptions are processed temporarily and never permanently stored.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="text-center">
                <Lock className="h-8 w-8 text-blue-500 mx-auto mb-2" />
                <CardTitle className="text-lg">Secure Processing</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground text-center">
                  All data is encrypted in transit and processed in secure, isolated environments.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="text-center">
                <Users className="h-8 w-8 text-purple-500 mx-auto mb-2" />
                <CardTitle className="text-lg">GDPR Compliant</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground text-center">
                  Full compliance with GDPR and other data protection regulations worldwide.
                </p>
              </CardContent>
            </Card>
          </div>

          {/* Main Content */}
          <div className="prose prose-lg max-w-none">

            <h2 className="text-2xl font-bold mt-8 mb-4 flex items-center">
              <Eye className="h-6 w-6 mr-2 text-primary" />
              Information We Collect
            </h2>

            <div className="bg-muted/50 p-6 rounded-lg mb-6">
              <h3 className="text-lg font-semibold mb-3">Account Information</h3>
              <ul className="space-y-2 text-muted-foreground">
                <li>• Email address (for account creation and communication)</li>
                <li>• Name (if provided during registration)</li>
                <li>• Authentication tokens (for secure login)</li>
                <li>• Account preferences and settings</li>
              </ul>
            </div>

            <div className="bg-muted/50 p-6 rounded-lg mb-6">
              <h3 className="text-lg font-semibold mb-3">Analysis Reports</h3>
              <ul className="space-y-2 text-muted-foreground">
                <li>• Analysis results and feedback generated by our AI</li>
                <li>• Performance scores and improvement suggestions</li>
                <li>• Usage statistics (number of analyses performed)</li>
                <li>• Anonymized metadata for service improvement</li>
              </ul>
            </div>

            <div className="bg-red-50 border border-red-200 p-6 rounded-lg mb-6">
              <h3 className="text-lg font-semibold mb-3 text-red-800">What We DON'T Store</h3>
              <ul className="space-y-2 text-red-700">
                <li>• Your actual resume or CV content</li>
                <li>• Job descriptions you submit for analysis</li>
                <li>• Personal information from your documents</li>
                <li>• Temporary files after analysis completion</li>
              </ul>
            </div>

            <h2 className="text-2xl font-bold mt-8 mb-4 flex items-center">
              <Shield className="h-6 w-6 mr-2 text-primary" />
              How We Use Your Information
            </h2>

            <div className="space-y-4 mb-6">
              <div className="border-l-4 border-primary pl-4">
                <h3 className="font-semibold">Service Provision</h3>
                <p className="text-muted-foreground">
                  We use your information to provide AI-powered analysis of your documents, generate reports, and deliver personalized feedback.
                </p>
              </div>

              <div className="border-l-4 border-primary pl-4">
                <h3 className="font-semibold">Account Management</h3>
                <p className="text-muted-foreground">
                  Your email is used for account authentication, sending analysis reports, and important service updates.
                </p>
              </div>

              <div className="border-l-4 border-primary pl-4">
                <h3 className="font-semibold">Service Improvement</h3>
                <p className="text-muted-foreground">
                  Anonymized usage data helps us improve our AI models and service quality.
                </p>
              </div>
            </div>

            <h2 className="text-2xl font-bold mt-8 mb-4 flex items-center">
              <Lock className="h-6 w-6 mr-2 text-primary" />
              Data Security & Processing
            </h2>

            <div className="bg-green-50 border border-green-200 p-6 rounded-lg mb-6">
              <h3 className="text-lg font-semibold mb-3 text-green-800">Our Security Measures</h3>
              <ul className="space-y-2 text-green-700">
                <li>• <strong>Encryption in Transit:</strong> All data is encrypted using TLS 1.3</li>
                <li>• <strong>Temporary Processing:</strong> Documents are processed in memory and immediately discarded</li>
                <li>• <strong>Secure Infrastructure:</strong> Hosted on industry-leading cloud platforms with SOC 2 compliance</li>
                <li>• <strong>Access Controls:</strong> Strict access controls and monitoring for all systems</li>
                <li>• <strong>Regular Audits:</strong> Regular security audits and penetration testing</li>
              </ul>
            </div>

            <h2 className="text-2xl font-bold mt-8 mb-4">Third-Party Services</h2>

            <div className="bg-blue-50 border border-blue-200 p-6 rounded-lg mb-6">
              <h3 className="text-lg font-semibold mb-3 text-blue-800">Analytics</h3>
              <p className="text-blue-700 mb-3">
                We use privacy-friendly analytics to understand how our service is used and to improve user experience.
              </p>
              <ul className="space-y-2 text-blue-700">
                <li>• <strong>Data collected:</strong> Page views, feature usage, performance metrics</li>
                <li>• <strong>Privacy features:</strong> IP anonymization, data retention limits</li>
                <li>• <strong>GDPR compliance:</strong> Full GDPR compliance with easy opt-out options</li>
                <li>• <strong>No personal data:</strong> No personally identifiable information is tracked</li>
              </ul>
            </div>

            <h2 className="text-2xl font-bold mt-8 mb-4">Your Rights Under GDPR</h2>

            <div className="grid md:grid-cols-2 gap-6 mb-6">
              <div className="space-y-4">
                <div className="bg-muted/50 p-4 rounded-lg">
                  <h3 className="font-semibold mb-2">Right to Access</h3>
                  <p className="text-sm text-muted-foreground">
                    Request a copy of all personal data we hold about you.
                  </p>
                </div>

                <div className="bg-muted/50 p-4 rounded-lg">
                  <h3 className="font-semibold mb-2">Right to Rectification</h3>
                  <p className="text-sm text-muted-foreground">
                    Correct any inaccurate or incomplete personal data.
                  </p>
                </div>

                <div className="bg-muted/50 p-4 rounded-lg">
                  <h3 className="font-semibold mb-2">Right to Erasure</h3>
                  <p className="text-sm text-muted-foreground">
                    Request deletion of your personal data ("right to be forgotten").
                  </p>
                </div>
              </div>

              <div className="space-y-4">
                <div className="bg-muted/50 p-4 rounded-lg">
                  <h3 className="font-semibold mb-2">Right to Portability</h3>
                  <p className="text-sm text-muted-foreground">
                    Export your data in a machine-readable format.
                  </p>
                </div>

                <div className="bg-muted/50 p-4 rounded-lg">
                  <h3 className="font-semibold mb-2">Right to Object</h3>
                  <p className="text-sm text-muted-foreground">
                    Object to processing of your personal data for specific purposes.
                  </p>
                </div>

                <div className="bg-muted/50 p-4 rounded-lg">
                  <h3 className="font-semibold mb-2">Right to Restrict</h3>
                  <p className="text-sm text-muted-foreground">
                    Limit how we process your personal data in certain circumstances.
                  </p>
                </div>
              </div>
            </div>

            <h2 className="text-2xl font-bold mt-8 mb-4">Cookie Policy</h2>

            <div className="bg-muted/50 p-6 rounded-lg mb-6">
              <p className="mb-4">We use minimal, essential cookies to provide our service:</p>
              <ul className="space-y-2 text-muted-foreground">
                <li>• <strong>Authentication cookies:</strong> To keep you logged in securely</li>
                <li>• <strong>Session cookies:</strong> To maintain your session during analysis</li>
                <li>• <strong>Preference cookies:</strong> To remember your settings and preferences</li>
                <li>• <strong>Analytics cookies:</strong> analytics (can be opted out)</li>
              </ul>
              <p className="mt-4 text-sm">
                You can manage cookie preferences in your browser settings. Disabling essential cookies may affect service functionality.
              </p>
            </div>

            <h2 className="text-2xl font-bold mt-8 mb-4">Data Retention</h2>

            <div className="space-y-4 mb-6">
              <div className="border-l-4 border-red-500 pl-4">
                <h3 className="font-semibold">Uploaded Documents</h3>
                <p className="text-muted-foreground">
                  <strong>Retention period:</strong> Immediately deleted after processing (typically within minutes)
                </p>
              </div>

              <div className="border-l-4 border-blue-500 pl-4">
                <h3 className="font-semibold">Account Information</h3>
                <p className="text-muted-foreground">
                  <strong>Retention period:</strong> Until account deletion or 2 years of inactivity
                </p>
              </div>

              <div className="border-l-4 border-green-500 pl-4">
                <h3 className="font-semibold">Analysis Reports</h3>
                <p className="text-muted-foreground">
                  <strong>Retention period:</strong> Until account deletion or upon request
                </p>
              </div>
            </div>

            {/* <h2 className="text-2xl font-bold mt-8 mb-4 flex items-center">
              <Mail className="h-6 w-6 mr-2 text-primary" />
              Contact Us
            </h2>

            <div className="bg-primary/5 p-6 rounded-lg mb-6">
              <p className="mb-4">
                If you have any questions about this privacy policy or want to exercise your rights, please contact us:
              </p>
              <div className="space-y-2">
                <p><strong>Email:</strong> privacy@ResumeBolt.com</p>
                <p><strong>Data Protection Officer:</strong> dpo@ResumeBolt.com</p>
                <p><strong>Address:</strong> ResumeBolt Privacy Team, 123 AI Street, Tech City, TC 12345</p>
              </div>
            </div> */}

            <h2 className="text-2xl font-bold mt-8 mb-4">Changes to This Policy</h2>

            <div className="bg-muted/50 p-6 rounded-lg mb-6">
              <p className="mb-4">
                We may update this privacy policy from time to time to reflect changes in our practices or for legal compliance.
                When we make changes:
              </p>
              <ul className="space-y-2 text-muted-foreground">
                <li>• We'll update the "Last updated" date at the top of this policy</li>
                <li>• For significant changes, we'll notify you via email or in-app notification</li>
                <li>• Your continued use of the service constitutes acceptance of the updated policy</li>
                <li>• Previous versions will be archived and available upon request</li>
              </ul>
            </div>

            <div className="text-center mt-12 p-8 bg-gradient-to-r from-primary/10 to-blue-600/10 rounded-lg">
              <h3 className="text-xl font-semibold mb-4">Questions About Your Privacy?</h3>
              <p className="text-muted-foreground mb-6">
                We're here to help. Contact our privacy team with any questions or concerns.
              </p>
              <Link href="https://www.linkedin.com/in/sahilfruitwala/" target="_blank">
              <Button size="lg">
                Contact Privacy Team
                <Mail className="ml-2 h-4 w-4" />
              </Button>
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t bg-background">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <Link href="/" className="flex items-center space-x-2">
              <Brain className="h-6 w-6 text-primary" />
              <span className="text-lg font-bold">ResumeBolt</span>
              </Link>
            </div>
            <div className="flex space-x-6 text-sm text-muted-foreground">
              <Link href="/" className="hover:text-primary transition-colors">Home</Link>
              <Link href="/privacy" className="hover:text-primary transition-colors">Privacy Policy</Link>
              {/* <a href="#" className="hover:text-primary transition-colors">Terms of Service</a> */}
              <a href="https://www.linkedin.com/in/sahilfruitwala/" className="hover:text-primary transition-colors">Contact</a>
            </div>
          </div>
          <div className="text-center text-sm text-muted-foreground mt-4">
            <p>&copy; 2025 ResumeBolt. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}